version: "3.9"
services:
  laravel_app:
    build:
      context: ./laravel_project
      dockerfile: ../laravel/Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./laravel_project:/var/www/html
    depends_on:
      - mysql_db
    command: php artisan serve --host=0.0.0.0 --port=8000


  svelte_app:
    build:
      context: ./svelte-app
      dockerfile: ../svelte/Dockerfile
    container_name: svelte_app
    ports:
      - "5173:5173"
    volumes:
      - ./svelte-app:/app
    command: npm run dev -- --host
    depends_on:
      - laravel_app

  mysql_db:
    image: mysql:8.4
    container_name: mysql_db
    command: --innodb_use_native_aio=0 --disable-log-bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    depends_on:
      - mysql_db

volumes:
  mysql_data:

